/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sorting */

#ifndef _Included_Sorting
#define _Included_Sorting
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sorting
 * Method:    sort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_Sorting_sort
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
