/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Except */

#ifndef _Included_Except
#define _Included_Except
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Except
 * Method:    catchThrow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Except_catchThrow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
