/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Memcall */

#ifndef _Included_Memcall
#define _Included_Memcall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Memcall
 * Method:    call
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Memcall_call
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
